
DROP INDEX PK_CATEGORY;

/* 카테고리 */
DROP TABLE CATEGORY 
  CASCADE CONSTRAINTS;

/* 카테고리 */
CREATE TABLE CATEGORY (
  CATEGORY_NO NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1), /* 카테고리번호 */
  CATEGORY_NM VARCHAR2(100) NOT NULL, /* 카테고리명 */
  TOP_NO NUMBER, /* 상위카테고리번호 */
  REG_DT DATE DEFAULT SYSDATE, /* 등록일 */
  MOD_DT DATE DEFAULT SYSDATE, /* 수정일 */
  STATUS NUMBER DEFAULT 1 /* 상태값 */
);

COMMENT ON TABLE CATEGORY IS '카테고리';

COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '카테고리번호';

COMMENT ON COLUMN CATEGORY.CATEGORY_NM IS '카테고리명';

COMMENT ON COLUMN CATEGORY.TOP_NO IS '상위카테고리번호';

COMMENT ON COLUMN CATEGORY.REG_DT IS '등록일';

COMMENT ON COLUMN CATEGORY.MOD_DT IS '수정일';

COMMENT ON COLUMN CATEGORY.STATUS IS '상태값';

CREATE UNIQUE INDEX PK_CATEGORY
  ON CATEGORY (
    CATEGORY_NO ASC
  );

ALTER TABLE CATEGORY
  ADD
    CONSTRAINT PK_CATEGORY
    PRIMARY KEY (
      CATEGORY_NO
    );