DROP INDEX PK_PRODUCT;

/* 상품 */
DROP TABLE PRODUCT 
  CASCADE CONSTRAINTS;

/* 상품 */
CREATE TABLE PRODUCT (
  ITEM_NO NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1), /* 상품번호 */
  NAME VARCHAR2(100) NOT NULL, /* 상품명 */
  PRICE NUMBER(7) DEFAULT 0 NOT NULL, /* 가격 */
  QUANTITY NUMBER DEFAULT 0, /* 재고 */
  CATEGORY_NO NUMBER, /* 카테고리번호 */
  IMAGE_NO NUMBER, /* 이미지번호 */
  PRODUCTION VARCHAR2(100) NOT NULL, /* 생산지 */
  WEIGHT NUMBER DEFAULT 0 NOT NULL, /* 중량/무게 */
  EXPIRED DATE NOT NULL, /* 유통기한 */
  DETAIL CLOB, /* 상품설명 */
  DISCOUNT NUMBER(2) DEFAULT 0, /* 할인율 */
  FINAL_PRICE NUMBER(7) DEFAULT 0, /* 최종가격 */
  SALES NUMBER DEFAULT 0 NOT NULL, /* 판매량 */
  REG_DT DATE DEFAULT SYSDATE, /* 상품등록일 */
  MOD_DT DATE DEFAULT SYSDATE /* 상품수정일 */
);

COMMENT ON TABLE PRODUCT IS '상품';

COMMENT ON COLUMN PRODUCT.ITEM_NO IS '상품번호';

COMMENT ON COLUMN PRODUCT.NAME IS '상품명';

COMMENT ON COLUMN PRODUCT.PRICE IS '가격';

COMMENT ON COLUMN PRODUCT.QUANTITY IS '재고';

COMMENT ON COLUMN PRODUCT.CATEGORY_NO IS '카테고리번호';

COMMENT ON COLUMN PRODUCT.IMAGE_NO IS '이미지번호';

COMMENT ON COLUMN PRODUCT.PRODUCTION IS '생산지';

COMMENT ON COLUMN PRODUCT.WEIGHT IS '중량/무게';

COMMENT ON COLUMN PRODUCT.EXPIRED IS '유통기한';

COMMENT ON COLUMN PRODUCT.DETAIL IS '상품설명';

COMMENT ON COLUMN PRODUCT.DISCOUNT IS '할인율';

COMMENT ON COLUMN PRODUCT.FINAL_PRICE IS '최종가격';

COMMENT ON COLUMN PRODUCT.SALES IS '판매량';

COMMENT ON COLUMN PRODUCT.REG_DT IS '상품등록일';

COMMENT ON COLUMN PRODUCT.MOD_DT IS '상품수정일';

CREATE UNIQUE INDEX PK_PRODUCT
ON PRODUCT (
    ITEM_NO ASC
);

ALTER TABLE PRODUCT
ADD
    CONSTRAINT PK_PRODUCT
    PRIMARY KEY (
        ITEM_NO
);

ALTER TABLE PRODUCT
ADD
    CONSTRAINT FK_CATEGORY_TO_PRODUCT
    FOREIGN KEY (
        CATEGORY_NO
    )
    REFERENCES CATEGORY (
        CATEGORY_NO 
    ) ON DELETE SET NULL  -- 참조 무결성 (부모 테이블의 CATEGORY_NO 값이 delete되면 null로 수정)
;